name: Test

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12.6
      - name: Install Poetry and Run
        run: |
          pip3 install poetry
          poetry env use 3.12.6
          poetry install
          poetry run pytest tests/
